### PR TITLE
Update tests to support Django versions 3.1 and 3.2.

### LINKED ISSUE #44: Add support for Django 3.1
First of all: thank you for this project - I hope it is still somewhat maintained.

According to the [Django documentation](https://www.djangoproject.com/download/#supported-versions) support for version 3.0 is dropped in one month (and 3.2 LTS should be released soon).

When I upgrade my Django application from v3.0.x to v3.1.x I get the following error when attempting to run the server:

```console
dev@vm:~$ python manage.py runserver

[..]

[..]/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 117, in _decorator
    middleware = middleware_class(view_func, *m_args, **m_kwargs)
TypeError: __init__() got multiple values for argument 'key_prefix'
```
which is coming from the @cache_page decorator:
```python
from fancy_cache import cache_page
from myproject.utils import cache

[..]

@cache_page(TTL, key_prefix=cache.cache_prefixer)
def my_view(...):
    [..]
```

It works as expected with Django <= 3.0.x.

### PR DESCRIPTION
**Pull request by YPCrumble**
Supports Python versions 3.5 - 3.9.
Fixes #44.

### CODE REVIEW

**Comment by peterbe** [comment]
Can you merge in the latest upstream `master` into this branch now that https://github.com/peterbe/django-fancy-cache/pull/48 has landed.

**Comment by YPCrumble** [comment]
Will do! I only have one version of python installed in my virtualenv locally so wanted to use CI to run the tests anyway - thank you for #48 !

**Comment by YPCrumble** [comment]
@peterbe looks like I need approval to get the workflow to run? If the tests don't pass I can take a look at what updates need making later this afternoon.

**Comment by YPCrumble** [comment]
@peterbe CI passed but it appears the tests aren't running properly - on my local I get output like `Ran 18 tests in xxxx seconds` `OK` and that doesn't seem to be showing up in CI - also the CI suite appears to be running way too quickly to be actually running the tests.

**Comment by peterbe** [comment]
I created a virtualenv, locally, based on Py 3.8. Now I can type:
```
pip install -U pip wheel tox
tox -e py38-dj22
```
and then all tests pass. And it says `Ran 18 tests in 0.024s`.

But if I type:
```
py38-dj32
```
tests fail. And that's where your challenge starts :)

**Comment by peterbe** [comment]
As of https://github.com/peterbe/django-fancy-cache/pull/49 try to merge in `master` again and retry.

**Comment by YPCrumble** [comment]
@peterbe apparently I still need approval for the workflow to rerun :/.

**Comment by YPCrumble** [comment]
@peterbe looks like they're running on my fork and failing so I can dig in and fix those issues and will ping you when I need that approval!

**Comment by YPCrumble** [comment]
@peterbe would you approve the workflow? Seems there was only one small fix to make things work for Django 3.1 and 3.2, and then another to make PyPy tests work. I believe this should pass CI!

**Comment by peterbe** [comment]
> @peterbe would you approve the workflow? Seems there was only one small fix to make things work for Django 3.1 and 3.2, and then another to make PyPy tests work. I believe this should pass CI!

Now you're no longer a first-time contributor! Thanks!

**Pull request merged**
