### PR TITLE
Feature/save n days of cache values

### LINKED ISSUE #36: FANCY_REMEMBER_ALL_URLS option and performance over time
Are there known limitations to this option? I had enabled it to give more visibility to our system and at about ~22,000 entries, the endpoints that were being tracked stopped being functional. Clearing the `fancy-urls` key solved the issue immediately.

```
In [1]: v = cache.get('fancy-urls')

In [2]: len(v.keys())
Out[2]: 22717
```

Above was the final count before deleting the key.

### PR DESCRIPTION
**Pull request by YPCrumble**
@peterbe this is a WIP PR aiming to fix #36. The basic gist is that we have an optional setting, `FANCY_CACHE_N_DAYS`, which limits the number of days that we cache the dict.

If `FANCY_CACHE_N_DAYS` is set, we use a new cache key each calendar date: `fancy-urls-2020-01-28`, `fancy-urls-2020-01-29`, etc. Each of these keys is saved for a `duration` of N days.

When pulling the cache, we use the `fancy_cache.utils.get_remembered_urls` function that creates the equivalent of the current `REMEMBERED_URLS_KEY` dict by merging N of the "daily" cache dicts.

When deleting a key from the cache, we check each of the N dicts and make sure the key is deleted from each.

When saving to the cache, we simply add the entry to the current day's cache entry. This means that cache entries could be duplicated each day, but this isn't a big deal as we're automatically "dropping" old cache entries after N days (i.e., `duration` mentioned above).

I also added a few MyPy type hints to aid in programming and moved constants to their own file; let me know if making a separate PR for those changes would help simplify this one if it's too unwieldy to review.

Would love any thoughts or feedback you have on the approach! Thanks again for your tremendous code reviews, and for maintaining this repo. I really appreciate it.

### CODE REVIEW

**Comment by YPCrumble** [comment]
@peterbe also note that this includes the commit from #60; I'd like to merge this after that PR and built this one off of that one.

**Comment by YPCrumble** [comment]
@peterbe I updated this PR per the two we just merged and added some documentation. Ready for review when you find time, thank you again for all your help reviewing these PR's!

**Review by peterbe — COMMENTED** [review]
It's hard to read the diff because it changes so much. I like the typing hints but I'm struggling to keep up with you :)

I don't really remember what the problem was. I'm guessing it was that using a static cache key (`fancy-cache`) and it just gets larger and larger. 

Your solution is that the individual day gets larger and larger. 
But any remembered URL coming in at 00:15 after midnight will get treated very differently from one coming in at 23:45 the same day. Seems unfair. And why use days? What about weeks or hours?

Have you considered storing the things differently instead?
Instead of:
```python
remembered_urls[url] = cache_key
```
you do:

```python
remembered_urls[url] = (int(time.time()), cache_key)
```
Then, before put it back into `self.cache.set` you do:
```
self.cache.set('fancy-cache', filtered(rememebered_urls, MAX_REMEMBERED_URLS), LONG_TIME)

...

def filtered(mapping, max=0):
  if not max: 
    return mapping
  flat = [(v[0], v[1], k) for k, v in mapping.items()]
  flat.sort()
  return {v[2]: (v[0], v[1]) for v in flat[:max]}
```

Basically, you take 
```
{
  url1: (1234, 'some value'),
  url2: (1235, 'some value'),
  url3: (1236, 'some value'),
}
```
and transform that to:
```
{
  url3: (1236, 'some value'),
  url2: (1235, 'some value'),
}
```

And then maybe something like:

```python
def get_remembered_urls() -> typing.Dict[str, str]:
    remembered_urls = cache.get(REMEMBERED_URLS_KEY, {})
    return  {k:v[1] for k, v in remembered_urls.items()}
```

That way, it won't keep remembering really old entries. 
Another approach, instead of using `MAX_REMEMBERED_URLS` could be `MAX_REMEMBERED_URL_AGE_SECONDS` and then the filter function will be something like:

```python
def filtered(mapping, max_age_seconds=0):
  if not max_age_seconds: 
    return mapping
  cutoff = time.time() - max_age_seconds
  return {k: v for k, v in mapping.items() if v[0] > cutoff}
```

What do you think?

**Comment by YPCrumble** [comment]
@peterbe thanks so much for the great review! 

I really like the idea. I avoided anything that would require looping through the remembered_urls dict because I wasn't sure how long that would take. But it seems that because this is using a dict comprehension it's going to be really fast, like less than a second for a million URLs. I have probably around 50k max so I don't think it should be an issue.

I'll pull the MyPy adjustments into a separate PR as they're easy to merge / don't affect functionality, and then make a pass with your suggested fix.

Thanks again for your help!!!

**Comment by YPCrumble** [comment]
@peterbe this is really helpful, thank you! Closing this PR in favor of #63 as the changes are quite different.

**Pull request closed without merging**
