### PR TITLE
Feature/new release

### PR DESCRIPTION
**Pull request by YPCrumble**
@peterbe preparing a release for once the other outstanding PR's are merged in. Thanks again for all your help updating this library!

### CODE REVIEW

**Review by peterbe — COMMENTED** [review]
I don't understand. But thanks for the updates regarding 1.2.0. 
Why is it duplicated in the README and in the changelog file?

**Comment by YPCrumble** [comment]
@peterbe about the duplication, I'm not sure. It appears that the changelog in the docs is out of date/abandoned so I tried to bring it up to date. If there's a way to automatically keep the changelog in both places that would be fantastic. Or does it make sense to just replace the changelog entries in the docs with a link to the GitHub changelog?

**Comment by peterbe** [comment]
> Or does it make sense to just replace the changelog entries in the docs with a link to the GitHub changelog?

A link would be perfectly fine. Thank you!

**Comment by YPCrumble** [comment]
@peterbe updated - I'll mark this PR as "Ready for review" once the other two PR's have been reviewed/merged.

**Comment by peterbe** [comment]
I slipped on the notifications for the other pull request reviews! Sorry. Feel free to ping me if it's been several days and I haven't reviewed.

**Review by peterbe — APPROVED** [review]
@YPCrumble Can you look it over one last time? It's been a while since you prepared this.

**Comment by YPCrumble** [comment]
@peterbe this is good to go! Looking forward to getting the release out :D. 

I'll continue to monitor closely as this app is very largely integrated into my production system...sometimes I wonder if it's too dependent on this app, or whether I'm relying on caching too much!

**Comment by peterbe** [comment]
Any idea what this was? https://github.com/peterbe/django-fancy-cache/runs/5761497729?check_suite_focus=true

**Comment by peterbe** [comment]
django-fancy-cache-1.2.0.tar.gz shipped to PyPI

**Comment by YPCrumble** [comment]
@peterbe thanks! The black issue was https://github.com/psf/black/issues/2964 - had a problem on my own sites as well. The `click` dependency for black wasn't pinned so an update caused black to crash.

In the future I suppose we could use dependabot to auto-upgrade black, but it seems like the tests are running again for now.

**Pull request merged**
