### PR TITLE
added:add multiple cache backend support

### PR DESCRIPTION
**Pull request by nbsky**
```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
        'TIMEOUT': 60,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    },
    'default2': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }

}

cache_page(60, cache=default2)
```

fixed:default2 failed to work properly

### CODE REVIEW

**Comment by peterbe** [comment]
Have you tested it in a project? Does it work awesomely now?

**Comment by nbsky** [comment]
yes , i add a unit test now.

**Comment by peterbe** [comment]
I can make a release if you want.

**Comment by peterbe** [comment]
See https://pypi.python.org/pypi/django-fancy-cache/0.8.1

**Comment by nbsky** [comment]
aha thankyou!

**Pull request merged**
