### PR TITLE
Python 3 compatibility.

### PR DESCRIPTION
**Pull request by skorokithakis**
This branch contains preliminary Python 3 compatibility.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Don't you just love Travis?

**Comment by peterbe** [comment]
Great work!! Yeah, how did we live before travis (or similar tools)!?
I don't like to include `six.py` into the source. This should be solved with a package dependency instead. All you need to do is add `install_requires=['six'],` to the `setup()` call in `setup.py`.

**Comment by skorokithakis** [comment]
Yeah, I didn't want to introduce the extra dependency, but, since Django requires it, it should be fine. I'll add it.

**Comment by skorokithakis** [comment]
Done. Can you push to PyPI after you merge? My Python 3 codebases are complaining!

**Comment by peterbe** [comment]
Something went wrong when I pushed that last time so PyPI was unfortunately not updated. I'm investigating.

**Comment by peterbe** [comment]
New release up on pypi now. It wasn't working in automation and I don't have time right now to dig deeper into it so I made a manual release.

**Comment by skorokithakis** [comment]
Thank you! I can now migrate TiThess to 3.4, fantastic!

**Pull request merged**
